name: i_detect
description: A prototype for a tracking and speed limit monitoring and alerting app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mqtt_client: ^10.0.0
  typed_data: ^1.3.2
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  dartz: ^0.10.1
  geolocator: ^9.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_maps_flutter: ^2.4.0
  flutter_native_splash: ^2.3.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  very_good_analysis: ^5.0.0+1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: "assets/images/splash_background.png"

flutter_native_splash:
  background_image: "assets/images/splash_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/certificates/
    - assets/images/
    - .env
